config/routes.rb
Rails.application.routes.draw do
  resources :owners

  resources :inventories

  resources :finances do
    collection do
      get :finance_table
    end
  end

  resources :quotes do
    member do
      get :quote_price
    end
  end

  resources :customers

  resources :staffs

  resources :cars do
    collection do
      get :inventory
    end
    member do
      get :price_cal
    end
  end

  root 'quotes#index'

end

app/models/staff.rb
class Staff < ActiveRecord::Base
  has_many :quotes
  has_many :customers

  def staff_info
    "#{name}, #{position}"
  end
  def self.salesperson
    Staff.where(position: 'Salesperson')

  end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :position)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <%= f.label "Position", class: 'control-label' %>
    <div class="controls">
      <%= f.select(:position, options_for_select([['Salesperson','Salesperson'], ['Finance Manager', 'Finance Manager'], ['Inventory Manager', 'Inventory Manager']]), { include_blank: true }) %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form' %>
<table>
  <thead>
   <tr>
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Show', @staff %></li></ul></div></th> |
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', staffs_path %></li></ul></div></th>
  </tr>
 </thead>
</table>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Staffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.position %></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Show', staff %></li></ul></div></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Edit', edit_staff_path(staff) %></li></ul></div></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></li></ul></div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="left">
<div class="nav-container2">
  <ul class="nav2">
    <li class="active2">
      <%= link_to 'New', new_staff_path %></li>
  </ul>
</div>
</div>

app/views/staffs/new.html.erb
<h1>New Staff Member</h1>

<%= render 'form' %>

<div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', staffs_path %></li></ul></div>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @staff.position %>
</p>
<table>
 <thead>
  <tr>
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Edit', edit_staff_path(@staff) %></li></ul></div></th> |
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', staffs_path %></li></ul></div></th>
  </tr>
 </thead>
</table>