config/routes.rb
Rails.application.routes.draw do
  resources :owners

  resources :inventories

  resources :finances do
    collection do
      get :finance_table
    end
  end

  resources :quotes do
    member do
      get :quote_price
    end
  end

  resources :customers

  resources :staffs

  resources :cars do
    collection do
      get :inventory
    end
    member do
      get :price_cal
    end
  end

  root 'quotes#index'

end

app/models/finance.rb
class Finance < ActiveRecord::Base
  has_many :customers
  belongs_to :quote



  def tax
    self.sales_tax = 0.043
  end




  def self.calculate_finance_table(quote_price = 0,interest_rate = 0,sales_tax = 0.043)
    Rails.logger.debug "Inputs: #{quote_price} #{interest_rate} #{sales_tax}"
    price_3 = []

      price_3 << ((quote_price + (quote_price * sales_tax))*interest_rate * (1+ (interest_rate) * 3))/(12 * 3)
    price_4 = []
      price_4 << ((quote_price + (quote_price * sales_tax))*interest_rate * (1+ (interest_rate) * 4))/(12 * 4)
    price_5 = []
      price_5 << ((quote_price + (quote_price * sales_tax))*interest_rate * (1+ (interest_rate) * 5))/(12 * 5)

    return price_3
    return price_4
    return price_5
  end



  def calculate_finance_table
    return self.class.calculate_finance_table(self.quote_price,self.interest_rate,self.sales_tax)
  end
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  # GET /finances
  # GET /finances.json
  def index
  @finances = Finance.all

  end

  # GET /finances/1
  # GET /finances/1.json
  def show
    @price_3_array = @finance.calculate_finance_table
    @price_4_array = @finance.calculate_finance_table
    @price_5_array = @finance.calculate_finance_table
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to @finance, notice: 'Finance was successfully created.' }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1
  # PATCH/PUT /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to @finance, notice: 'Finance was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance.destroy
    respond_to do |format|
      format.html { redirect_to finances_url, notice: 'Finance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def finance_table
    interest = params[:interest]
    tax = params[:tax]
    car_price = params[:car]
    @price_3_array = Finance.calculate_finance_table(quote_price.to_i, tax.to_i, interest.to_f)
    @price_4_array = Finance.calculate_finance_table(quote_price.to_i, tax.to_i, interest.to_f)
    @price_5_array = Finance.calculate_finance_table(quote_price.to_i, tax.to_i, interest.to_f)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_params
      params.require(:finance).permit(:interest_rate, :sales_tax, :customer_id, :quote_id, :quote_price)
    end
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/views/finances/_finance_table.erb
<table class="CSSTableGenerator" width="30%">
  <th>Price</th>
  <th>Interest Rate</th>
  <th>Sales Tax</th>
  <th>3 Years</th>
  <th>4 Years</th>
  <th>5 Years</th>
  <tbody>
      <tr>
        <td><%= @price_3_array%></td>
        <td><%= @price_4_array%></td>
        <td><%= @price_5_array%></td>
      </tr>

 </tbody>
</table>

app/views/finances/_form.html.erb
<%= form_for(@finance) do |f| %>
  <% if @finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% @finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="control-group">
      <%= f.label "Customer Name", class: 'control-label' %>
      <div class="controls">
        <%= collection_select nil, :customer_id, Customer.all, :id, :name  %>
      </div>
    </div>
    <div class="field">
      <%= f.label :quote_price %><br>
      <%= f.text_field :quote_price %>
    </div>
  <div class="field">
    <%= f.label :interest_rate %><br>
    <%= f.text_field :interest_rate %>
  </div>
  <div class="field">
    <%= f.label :sales_tax %><br>
    <%= f.text_field :tax %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form' %>
<table>
 <thead>
  <tr>
  <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Show', @finance %></li></ul></div></th> |
  <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', finances_path %></li></ul></div></th>
  </tr>
 </thead>
</table>

app/views/finances/finance.js.erb
$('#finance-table').html("<%= j (render 'finance_table') %>")

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Finances Options</h1>
<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Interest Rate</th>
      <th>Sales Tax </th>
      <th>3 Years</th>
      <th>4 Years</th>
      <th>5 Years</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @finances.each do |finance| %>
      <tr>
        <td><%= number_to_currency(finance.quote_price) %></td>
        <td><%= number_to_percentage(finance.interest_rate) %></td>
        <td><%= number_to_percentage(finance.tax) %></td>
        <td><%= @price_3_array%></td>
        <td><%= @price_4_array%></td>
        <td><%= @price_5_array%></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><td><%= link_to 'Show', finance %></li></ul></div></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><td><%= link_to 'Edit', edit_finance_path(finance) %></li></ul></div></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></li></ul></div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="left">
  <div class="nav-container2">
    <ul class="nav2">
      <li class="active2">
        <%= link_to 'New Finance', new_finance_path %>
      </li>
    </ul>
  </div>
</div>

app/views/finances/new.html.erb
<h1>New Finance</h1>

<%= render 'form' %>

<div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', finances_path %></li></ul></div>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Interest rate:</strong>
  <%= @finance.interest_rate %>
</p>

<p>
  <strong>Sales tax:</strong>
  <%= @finance.sales_tax %>
</p>



<table>
  <thead>
   <tr>
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Edit', edit_finance_path(@finance) %></li></ul></div></th> |
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', finances_path %></li></ul></div></th>
   </tr>
  </thead>
</table>