config/routes.rb
Rails.application.routes.draw do
  resources :owners

  resources :inventories

  resources :finances do
    collection do
      get :finance_table
    end
  end

  resources :quotes do
    member do
      get :quote_price
    end
  end

  resources :customers

  resources :staffs

  resources :cars do
    collection do
      get :inventory
    end
    member do
      get :price_cal
    end
  end

  root 'quotes#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :customer
  belongs_to :car
  belongs_to :staff
  has_many :finances
  has_one :owner

  def quote_price
      "#{price}"
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end
  def quote_price
    quote = Quote.find(params[:id])
    render json:quote.quote_price

  end
  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:car_id, :customer_id, :staff_id, :price, :quote_date, :status)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :Select_A_Car %><br>
      <%= f.collection_select :car_id, Car.available, :id, :car_info  %>
    </div>
  <div class="field">
    <%= f.label :New_Customer %><br>
    <td><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'ADD', new_customer_path %></li></ul></div></td>
  </div>
    <div class="field">
      <%= f.label :Customer_Name %><br>
      <%= f.collection_select :customer_id, Customer.all, :id, :name %>
    </div>
  <div class="field">
    <%= f.label :Sales_Person %><br>
    <%= f.collection_select :staff_id, Staff.salesperson, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :quote_date %><br>
    <%= f.date_select :quote_date %>
  </div>
    <div class="control-group">
      <%= f.label "Status", class: 'control-label' %>
      <div class="controls">
        <%= f.select(:status, options_for_select([['Pending', 'Pending'], ['Sold', 'Sold']]), { include_blank: true }) %>
      </div>
    </div>
    <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>
<table>
 <thead>
  <tr>
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Show', @quote %></li></ul></div></th>|
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', quotes_path %></li></ul></div></th>
  </tr>
 </thead>
</table>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Make A Quote</h1>

<table>
  <thead>
    <tr>
      <th>Car</th>
      <th>Customer</th>
      <th>Staff</th>
      <th>Price</th>
      <th>Quote date</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.car.car_info %></td>
        <td><%= quote.customer.name %></td>
        <td><%= quote.staff.name %></td>
        <td><%= number_to_currency(quote.car.price_cal) %></td>
        <td><%= quote.quote_date %></td>
        <td><%= quote.status %></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Show', quote %></li></ul></div></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Edit', edit_quote_path(quote) %></li></ul></div></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></li></ul></div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="left">
<div class="nav-container2">
  <ul class="nav2">
    <li class="active2">
    <%= link_to 'New Quote', new_quote_path %>
    </li>
  </ul>
</div>
</div>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', quotes_path %></li></ul></div>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car:</strong>
  <%= @quote.car.car_info %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.name %>
</p>

<p>
  <strong>Staff:</strong>
  <%= @quote.staff.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @quote.price %>
</p>

<p>
  <strong>Quote date:</strong>
  <%= @quote.quote_date %>
</p>
<p>
  <strong>Quote status:</strong>
  <%= @quote.status %>
</p>
<table>
 <thead>
  <tr>
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Edit', edit_quote_path(@quote) %></li></ul></div></th> |
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', quotes_path %></li></ul></div></th>
  </tr>
 </thead>
</table>