config/routes.rb
Rails.application.routes.draw do
  resources :owners

  resources :inventories

  resources :finances do
    collection do
      get :finance_table
    end
  end

  resources :quotes do
    member do
      get :quote_price
    end
  end

  resources :customers

  resources :staffs

  resources :cars do
    collection do
      get :inventory
    end
    member do
      get :price_cal
    end
  end

  root 'quotes#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :quotes


  def self.available
    Car.where(status: 'Available')
  end

  def price_cal
    self.price = (whole_sale_price * 1.1);
  end

  def car_info
    "#{make}, #{model}, #{color}, #{status}"
  end



end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end
  def inventory
    @cars = Car.all
  end
  def price_cal
    car = Car.find(params[:id])
    render json:car.price_cal

  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:make, :model, :color, :vin, :whole_sale_price, :price, :status)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="field">
    <%= f.label :whole_sale_price %><br>
    <%= f.text_field :whole_sale_price %>
  </div>
    <div class="control-group">
      <%= f.label "Status", class: 'control-label' %>
      <div class="controls">
        <%= f.select(:status, options_for_select([['Available','Available'], ['Pending', 'Pending'], ['Sold', 'Sold']]), { include_blank: true }) %>
      </div>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>
 <table>
  <thead>
   <tr>
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Show', @car %></li></ul></div></th>
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', cars_path %></li></ul></div></th>
  </tr>
 </thead>
 </table>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Cars</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Color</th>
      <th>Vin</th>
      <th>Price</th>
      <th>Whole sale price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.color %></td>
        <td><%= car.vin %></td>
        <td><%= number_to_currency(car.price_cal) %></td>
        <td><%= number_to_currency(car.whole_sale_price) %></td>
        <td><%= car.status %></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Show', car %></li></ul></div></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Edit', edit_car_path(car) %></li></ul></div></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></li></ul></div></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="left">
<div class="nav-container2">
 <ul class="nav2">
  <li class="active2">
  <%= link_to 'New', new_car_path %>
  </li>
 </ul>
</div>
</div>

app/views/cars/inventory.html.erb
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<h1>Inventory</h1>
<table id="Inventory">
  <thead>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Color</th>
    <th>Vin</th>
    <th>Price</th>
    <th>Status</th>
  </tr>
  </thead>

  <tbody>
  <% @cars.each do |car| %>
      <tr>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.color %></td>
        <td><%= car.vin %></td>
        <td><%= number_to_currency(car.price_cal) %></td>
        <td><%= car.status %></td>
        <td><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Edit', edit_car_path(car) %></li></ul></div></td>

      </tr>
  <% end %>
  </tbody>
</table>
</body>
</html>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', cars_path %></li></ul></div>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<p>
  <strong>Whole sale price:</strong>
  <%= number_to_currency(@car.whole_sale_price) %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@car.price_cal) %>
</p>

<p>
  <strong>Status:</strong>
  <%= @car.status %>
</p>

<table>
 <thead>
  <tr>
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Edit', edit_car_path(@car) %></li></ul></div></th>
    <th><div class="nav-container2"><ul class="nav2"><li class="active2"><%= link_to 'Back', cars_path %></li></ul></div></th>
  </tr>
 </thead>
</table>